name: The Lazy Linker
description: Enriches a Pull Request with Jira information based on branch name
author: Trevor Pierce

# Define your inputs here.
inputs:
  github-token:
    description: Github token provided by Github Actions
    required: true

  jira-api-key:
    description: User API key from Jira
    required: true

  atlassian-org-name:
    description: Organization base url for Jira
    required: true

  jira-user-email:
    description: User email tied to API key from Jira
    required: true

  fail-when-jira-issue-not-found:
    description: Enabled to enforce a Jira key in the branch name
    required: false
    default: false

  description-character-limit:
    description: Limit the description from Jira to a specific character count
    required: false

runs:
  using: node20
  main: dist/index.js
